Repository openshift/cluster-olm-operator, pull requests merged in 2024-11, with the labels that each got.

#78 OPRUN-3588: Add OLMv1 capability annotation to manifests
  go.mod
  go.sum
  manifests/0000_51_olm_00-olm-operator.yml
  manifests/0000_51_olm_01_operator_namespace.yaml
  manifests/0000_51_olm_02_operator_clusterrole.yaml
  manifests/0000_51_olm_03_service_account.yaml
  manifests/0000_51_olm_04_metrics_service.yaml
  manifests/0000_51_olm_05_operator_clusterrolebinding.yaml
  manifests/0000_51_olm_06_deployment.yaml
  manifests/0000_51_olm_07_cluster_operator.yaml
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/console/v1/types_console_plugin.go
  vendor/github.com/openshift/api/console/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/console/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/api/console/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/features.md
  vendor/github.com/openshift/api/operator/v1/types_olm.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.crd-manifests/0000_10_operator-lifecycle-manager_01_olms-CustomNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.crd-manifests/0000_10_operator-lifecycle-manager_01_olms-DevPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.crd-manifests/0000_10_operator-lifecycle-manager_01_olms-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/build-machinery-go/OWNERS
  vendor/github.com/openshift/build-machinery-go/make/operator.example.mk.help.log
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/operator/mom.mk
  vendor/github.com/openshift/build-machinery-go/scripts/test-operator-integration.sh
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference

#82 NO-ISSUE: Remove library-go replaces and update clients.go for k8s 1.31
  go.mod
  go.sum
  pkg/clients/clients.go
  vendor/github.com/openshift/library-go/pkg/apiserver/jsonpatch/jsonpatch.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/base_controller.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/factory.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/interfaces.go
  vendor/github.com/openshift/library-go/pkg/crypto/crypto.go
  vendor/github.com/openshift/library-go/pkg/operator/deploymentcontroller/deployment_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/loglevel/logging_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/monitoring.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourcemerge/object_merger.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/admission.go
  vendor/github.com/openshift/library-go/pkg/operator/staticresourcecontroller/static_resource_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/status/status_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/canonicalize.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/informers.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/interfaces.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/test_helpers.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference

#86 NO-ISSUE: Add OCP variant annotations to manifests
  manifests/0000_51_olm_00-olm-operator.yml
  manifests/0000_51_olm_01_operator_namespace.yaml
  manifests/0000_51_olm_02_operator_clusterrole.yaml
  manifests/0000_51_olm_03_service_account.yaml
  manifests/0000_51_olm_04_metrics_service.yaml
  manifests/0000_51_olm_05_operator_clusterrolebinding.yaml
  manifests/0000_51_olm_06_deployment.yaml
  manifests/0000_51_olm_07_cluster_operator.yaml
Labels: lgtm, approved, jira/valid-reference

#85 NO-ISSUE: bump openshift/api dependency to fix scheme registration
  go.mod
  go.sum
  vendor/github.com/openshift/api/operator/v1/register.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference

#87 Revert "NO-ISSUE: Add OCP variant annotations to manifests"
  manifests/0000_51_olm_00-olm-operator.yml
  manifests/0000_51_olm_01_operator_namespace.yaml
  manifests/0000_51_olm_02_operator_clusterrole.yaml
  manifests/0000_51_olm_03_service_account.yaml
  manifests/0000_51_olm_04_metrics_service.yaml
  manifests/0000_51_olm_05_operator_clusterrolebinding.yaml
  manifests/0000_51_olm_06_deployment.yaml
  manifests/0000_51_olm_07_cluster_operator.yaml
Labels: lgtm, approved, jira/valid-reference

#88 NO-ISSUE: Add ocp variants annotations
  manifests/0000_51_olm_00-olm-operator.yml
  manifests/0000_51_olm_01_operator_namespace.yaml
  manifests/0000_51_olm_02_operator_clusterrole.yaml
  manifests/0000_51_olm_03_service_account.yaml
  manifests/0000_51_olm_04_metrics_service.yaml
  manifests/0000_51_olm_05_operator_clusterrolebinding.yaml
  manifests/0000_51_olm_06_deployment.yaml
  manifests/0000_51_olm_07_cluster_operator.yaml
Labels: lgtm, approved, jira/valid-reference

#89 OPRUN-3605: pkg/clients: correctly handle setting lastTransitionTime
  pkg/clients/clients.go
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#74 OPRUN-3401, OPRUN-3588: Update manifest annotations for GA
  go.mod
  go.sum
  manifests/0000_51_olm_00-olm-operator.yml
  manifests/0000_51_olm_01_operator_namespace.yaml
  manifests/0000_51_olm_02_operator_clusterrole.yaml
  manifests/0000_51_olm_03_service_account.yaml
  manifests/0000_51_olm_04_metrics_service.yaml
  manifests/0000_51_olm_05_operator_clusterrolebinding.yaml
  manifests/0000_51_olm_06_deployment.yaml
  manifests/0000_51_olm_07_cluster_operator.yaml
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/features.md
  vendor/github.com/openshift/api/operator/v1/types_olm.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.crd-manifests/0000_10_operator-lifecycle-manager_01_olms-DevPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.crd-manifests/0000_10_operator-lifecycle-manager_01_olms-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.crd-manifests/0000_10_operator-lifecycle-manager_01_olms.crd.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/api/operator/v1alpha1/types_olm.go
  vendor/github.com/openshift/api/operator/v1alpha1/zz_generated.featuregated-crd-manifests.yaml
  vendor/modules.txt
Labels: lgtm, approved, qe-approved, jira/valid-reference, acknowledge-critical-fixes-only

#90 OPRUN-3605: Updating to the latest commit of openshift/api
  go.mod
  go.sum
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/features.md
  vendor/github.com/openshift/api/operator/v1/types_csi_cluster_driver.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.crd-manifests/0000_50_csi-driver_01_clustercsidrivers.crd.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#92 OPRUN-3605: manifests: set `terminationMessagePolicy: FallbackToLogsOnError` for all containers
  manifests/0000_51_olm_06_deployment.yaml
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#91 NO-ISSUE: Adding Lalatendu Mohanty as approver
  OWNERS_ALIASES
Labels: lgtm, approved, jira/valid-reference
