Repository openshift/cluster-olm-operator, pull requests merged in 2024-07, with the labels that each got.

#57 NO-ISSUE: Update owners
  OWNERS_ALIASES
Labels: lgtm, approved, jira/valid-reference

#56 OCPBUGS-36684: Disable cluster-olm-operator
  Dockerfile
Labels: lgtm, approved, jira/severity-critical, jira/valid-reference, jira/valid-bug

#59 OPRUN-3437: update configmap permissions
  manifests/0000_51_olm_02_operator_clusterrole.yaml
Labels: lgtm, approved, jira/valid-reference

#60 OPRUN-3405: Stop building rukpak
  cmd/cluster-olm-operator/main.go
  manifests/0000_51_olm_06_deployment.yaml
  manifests/image-references
Labels: lgtm, approved, jira/valid-reference

#63 OPRUN-3403: Remove Rukpak references from code
  manifests/0000_51_olm_06_deployment.yaml
  pkg/controller/builder.go
Labels: lgtm, approved, jira/valid-reference

#62 OCPBUGS-37544: add version flag
  cmd/cluster-olm-operator/main.go
Labels: lgtm, approved, qe-approved, jira/valid-reference, jira/valid-bug, jira/severity-low
