Repository openshift/cluster-olm-operator, pull requests merged in 2025-04, with the labels that each got.

#114 OCPBUGS-54877: Increase debug logging level for op-con/catd
  manifests/0000_51_olm_00-olm-operator.yml
Labels: lgtm, approved, jira/valid-reference, jira/valid-bug

#116 OCPBUGS-48478: [release-4.18] Add openshift node selector annotation
  manifests/0000_51_olm_01_operator_namespace.yaml
Labels: lgtm, approved, qe-approved, cherry-pick-approved, backport-risk-assessed, jira/valid-reference, jira/valid-bug, jira/severity-moderate

#110 OPRUN-3821: Add FeatureFlag for OLMv1 Single/OwnNamespace
  go.mod
  go.sum
  internal/featuregates/mapper.go
  vendor/github.com/openshift/api/config/v1/types_authentication.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/features.md
  vendor/github.com/openshift/api/features/features.go
  vendor/github.com/openshift/api/image/v1/generated.proto
  vendor/github.com/openshift/api/image/v1/types.go
  vendor/github.com/openshift/api/image/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only
